### ISSUE TITLE
Can't use SCSS files written by utf-8.

### ISSUE THREAD

**Issue by ybrliiu** [jhthorsen/mojolicious-plugin-assetpack#70] opened 2016-02-11 17:29 UTC
Thanks for this great module.

I use CSS::Sass for compile SCSS files in this module,
but an error has occured like this.

[debug] AssetPack falls back to predefined mapping on: AssetPack could not generate base-0804c7faf243a24801b279e05af55c64.css (base.scss): Wide character in syswrite at .../perl5/perlbrew/perls/perl-5.22.1/lib/5.22.1/x86_64-linux/IO/Handle.pm line 483. {source_paths=[/...

This problem will solve just use Encode.pm,so please deal with utf-8 SCSS files.

And,I glat to set up when compile SCSS files,like CSS::Sass.

**Comment by zoffixznet** [comment] 2016-02-11 17:46
Can you provide a specific testcase we could run to reproduce the problem?

I tried having a 'wide character' in my CSS, saving file as both UTF-8 and UTF-8 with BOM and no issues occured neither with using `sass` nor `CSS::Sass`

**Comment by ybrliiu** [comment] 2016-02-11 18:08
Sorry,
X Can't use SCSS files written by utf-8.
↓
O Can't use SCSS files include without an alphanumeric characters.

this is testcase.

```
@charset "utf-8";
/* コメント */
h2 {
  color: #000000;
}
```

**Comment by zoffixznet** [comment] 2016-02-11 18:23
Thanks! I was able to reproduce the issue.

Changing [this line](https://github.com/jhthorsen/mojolicious-plugin-assetpack/blob/46f3f97913c144ea221214db431232e7f00ec33e/lib/Mojolicious/Plugin/AssetPack/Preprocessor/Scss.pm#L167) to 
```perl6
    ($$text, $err, my $srcmap) = CSS::Sass::sass_compile(encode 'UTF-8', $$text, %args);
```
(with `encode` being one from `Mojo::Util`) solves the issue. I'll leave it to @jhthorsen to figure out how to properly fix this and test.

**Comment by ybrliiu** [comment] 2016-02-11 18:33
Thank you for your response!

**Comment by ybrliiu** [comment] 2016-02-12 03:05
```
    ($$text, $err, my $srcmap) = CSS::Sass::sass_compile($$text, %args);
    $$text = encode('UTF-8', $$text);
```
Maybe this code is better.
If compile SCSS file import include not alphanumeric characters SCSS file,same error occured.

**Comment by jhthorsen** [comment] 2016-02-12 07:07
Sorry, I don't understand what is wrong. I tried to reproduce it in fbff25f, without any luck.

Care to clarify?

**Comment by ybrliiu** [comment] 2016-02-12 10:28
Sorry for bad English.
Please try this example.

```scss:70-utf-8.scss
@charset "UTF-8";
@import '70-utf8-import.scss';
/* コメント */
h2 {
  color: #000000;
}
```

```scss:70-utf8-import.scss
/* 読み込むファイル */
h3 {
  color:#ffffff;
}
```

This example is ok with above code.

**Comment by jhthorsen** [comment] 2016-02-12 10:34
Still nothing. Can you let me know which perl and CSS::Sass version you have?

**Comment by ybrliiu** [comment] 2016-02-12 10:48
perl v5.22.1
CSS::Sass 3.3.0

**Comment by jhthorsen** [comment] 2016-02-12 10:55
Thanks!

I was using CSS::Sass v3.2.2 which didn't have this issue. Do you know which change could've caused this @mgreter ?

**Comment by ybrliiu** [comment] 2016-02-12 10:57
Test code is this.

70-sass-utf8.t
```perl
use t::Helper;

my $t = t::Helper->t({minify => 0});
plan skip_all => 'CSS::Sass is required' unless eval 'require CSS::Sass;';
plan skip_all => 'Could not find preprocessors for sass' unless $t->app->asset->preprocessors->can_process('sass');

eval { $t->app->asset('scss.css' => '/sass/70-utf8.scss') };
is $@, '', 'built scss.css';

$t->get_ok('/test1')->status_is(200)->content_like(qr{コメント})->content_like(qr{読み込むファイル});

done_testing;
__DATA__
@@ test1.html.ep
%= asset 'scss.css', {inline => 1}
```

I run this code `prove -lc t/70-sass-utf8.t`
Result is
```
t/70-sass-utf8.t .. 1/? 
#   Failed test 'content is similar'
#   at t/70-sass-utf8.t line 10.
#                   '<style>/*<![CDATA[*/
# html:before{background:#f00;color:#fff;font-size:14pt;position:fixed;padding:20px;z-index:9999;content:"AssetPack could not generate 70-utf8-ba61a084135726b5fcc1e77f48d8879c.css (70-utf8.scss): Wide character in syswrite at ~/perl5/perlbrew/perls/perl-5.22.1/lib/5.22.1/x86_64-linux/IO/Handle.pm line 483.";}
# /*]]>*/</style>
# '
#     doesn't match '(?^:コメント)'
t/70-sass-utf8.t .. 5/? 
#   Failed test 'content is similar'
#   at t/70-sass-utf8.t line 10.
#                   '<style>/*<![CDATA[*/
# html:before{background:#f00;color:#fff;font-size:14pt;position:fixed;padding:20px;z-index:9999;content:"AssetPack could not generate 70-utf8-ba61a084135726b5fcc1e77f48d8879c.css (70-utf8.scss): Wide character in syswrite at ~/perl5/perlbrew/perls/perl-5.22.1/lib/5.22.1/x86_64-linux/IO/Handle.pm line 483.";}
# /*]]>*/</style>
# '
#     doesn't match '(?^:読み込むファイル)'
# Looks like you failed 2 tests of 5.
t/70-sass-utf8.t .. Dubious, test returned 2 (wstat 512, 0x200)
Failed 2/5 subtests 

Test Summary Report
-------------------
t/70-sass-utf8.t (Wstat: 512 Tests: 5 Failed: 2)
  Failed tests:  4-5
  Non-zero exit status: 2
Files=1, Tests=5,  3 wallclock secs ( 0.18 usr  0.02 sys +  1.93 cusr  0.15 csys =  2.28 CPU)
Result: FAIL
```

**Comment by ybrliiu** [comment] 2016-02-12 11:01
OK,I ask @mgreter.

**Comment by jhthorsen** [comment] 2016-02-12 11:06
@ybrliiu: We already did.

**Comment by ybrliiu** [comment] 2016-02-12 11:17
Sorry,I mistook.

**Comment by mgreter** [comment] 2016-02-12 17:34
@jhthorsen there were some changes in [sass.xs] [1] regarding unicode handling. Maybe some one who can reproduce can provide a failing test case and make a PR for [CSS::Sass] [2] (Just to be 100% sure the input has the intended encoding)? If I understand correctly, this was not happening in 3.2.2 and only in 3.3.0?

Probably have some time this weekend to have a look!

[1]: https://github.com/sass/perl-libsass/commit/d60f671fa470c9383ad20706b313689bfcd022ba#diff-94d35e901e089dacc490094c294518d9R757
[2]: https://github.com/sass/perl-libsass

**Comment by mgreter** [comment] 2016-02-12 17:57
Just made a short test with my current dev branch of perl-libsass:

```bash
$ psass 70-utf-8.scss -o output.css
$ psass -v
psass 0.4.0 (perl sass/scss compiler)
  libsass: 3.3.3-61-g68d1c6-dirty
  sass2scss: 1.0.5
```

Output looks correct and I don't get any warnings:

```css
@charset "UTF-8";
/* 読み込むファイル */
h3 {
  color: #ffffff; }

/* コメント */
h2 {
  color: #000000; }
```

When I output to console I get expected errors on my win machine since it uses CP850:

```bash
$ psass 70-utf-8.scss
"\x{8aad}" does not map to cp850 at C:\Strawberry\64\perl\site\bin/psass line 197.
"\x{307f}" does not map to cp850 at C:\Strawberry\64\perl\site\bin/psass line 197.
"\x{8fbc}" does not map to cp850 at C:\Strawberry\64\perl\site\bin/psass line 197.
"\x{3080}" does not map to cp850 at C:\Strawberry\64\perl\site\bin/psass line 197.
"\x{30d5}" does not map to cp850 at C:\Strawberry\64\perl\site\bin/psass line 197.
"\x{30a1}" does not map to cp850 at C:\Strawberry\64\perl\site\bin/psass line 197.
"\x{30a4}" does not map to cp850 at C:\Strawberry\64\perl\site\bin/psass line 197.
"\x{30eb}" does not map to cp850 at C:\Strawberry\64\perl\site\bin/psass line 197.
"\x{30b3}" does not map to cp850 at C:\Strawberry\64\perl\site\bin/psass line 197.
"\x{30e1}" does not map to cp850 at C:\Strawberry\64\perl\site\bin/psass line 197.
"\x{30f3}" does not map to cp850 at C:\Strawberry\64\perl\site\bin/psass line 197.
"\x{30c8}" does not map to cp850 at C:\Strawberry\64\perl\site\bin/psass line 197.
@charset "UTF-8";
/* \x{8aad}\x{307f}\x{8fbc}\x{3080}\x{30d5}\x{30a1}\x{30a4}\x{30eb} */
h3 {
  color: #ffffff; }

/* \x{30b3}\x{30e1}\x{30f3}\x{30c8} */
h2 {
  color: #000000; }
```

**Comment by jhthorsen** [comment] 2016-02-12 17:57
@mgreter: The "problem" is that I'm awful at unicode, so I have no idea if CSS::Sass "suddenly" started doing it correct, or if it's doing it wrong now...

What do you think @zoffixznet? Should I add the purposed change in this issue or create an issue for  https://github.com/sass/perl-libsass?

**Comment by mgreter** [comment] 2016-02-12 17:57
This example should IMHO show the behavior you get:

```perl
use utf8;
use strict;
use warnings;

use CSS::Sass qw(sass_compile);
use File::Slurp qw(write_file);

my $scss = <<SCSS;
\@charset "utf-8";
/* コメント */
h2 {
  color: #000000;
}
SCSS

my ($css, $err) = sass_compile($scss);

print "Writing file with utf8 encoding\n";
write_file( 'unicode-out.css', { binmode => ':utf8' }, $css ) ;
print "Writing file with raw encoding\n";
write_file( 'unicode-out.css', { binmode => ':raw' }, $css);
```
Results in
```
Writing file with utf8 encoding
Writing file with raw encoding
Wide character in syswrite at C:/Strawberry/64/perl/vendor/lib/File/Slurp.pm line 506.
```

**Comment by mgreter** [comment] 2016-02-12 18:00
I should probably point out more clearly that CSS::Sass always return a utf8 encoded string.
Also some parts of that got fixed with `3.3.0` since `psass` had some problems in `3.2.2`.
I hope you agree that this the sane thing to do, since libsass always uses utf8 as output.
If absolutely needed I could add an option to return a raw string with utf8 byte sequence.

**Comment by jhthorsen** [comment] 2016-02-12 18:00
Cool! I guess that tells us that I should take the change from https://github.com/jhthorsen/mojolicious-plugin-assetpack/issues/70#issuecomment-183159308

**Comment by mgreter** [comment] 2016-02-12 18:02
@jhthorsen it might be enough to just tell perl that the string is indeed an utf8 string. IMO perl only needs to switch an internal flag, since it stores unicode as utf8 internally anyway, so no actual conversion is needed (AFAIR TBH). I will try to dig out the documentation for that.

**Comment by jhthorsen** [comment] 2016-02-12 18:03
@mgreter: You don't have to do that. You've been more than helpful imo :smiley:

**Comment by mgreter** [comment] 2016-02-12 18:04
OK, I think [`utf8::upgrade`] [1] should point you in the right direction :smile: 

[1]: http://perldoc.perl.org/utf8.html

**Comment by jhthorsen** [comment] 2016-04-17 09:16
Sorry for the delay! This is now fixed in Mojolicious::Plugin::AssetPack::Pipe::Sass.

Thanks for all the input.

**Closed** 2016-04-17 09:15 UTC
Labels: bug

**Comment by ybrliiu** [comment] 2016-04-23 17:17
Thank you!
